from django.contrib import admin

from .models import Cart, CartItem


class CartItemInline(admin.TabularInline):
    """Display cart items inside their parent cart."""

    model = CartItem
    extra = 0

    fields = (
        "product",
        "variant",
        "quantity",
        "unit_price_display",
        "line_total_display",
        "created_at",
    )

    readonly_fields = (
        "unit_price_display",
        "line_total_display",
        "created_at",
    )

    show_change_link = True

    def has_add_permission(self, request, obj=None):
        """Cart items should be created through the storefront."""

        return False

    @admin.display(description="Unit Price")
    def unit_price_display(self, obj):
        if not obj.pk:
            return "—"

        return f"Rs. {obj.unit_price:,.2f}"

    @admin.display(description="Line Total")
    def line_total_display(self, obj):
        if not obj.pk:
            return "—"

        return f"Rs. {obj.line_total:,.2f}"


@admin.register(Cart)
class CartAdmin(admin.ModelAdmin):
    """Configure shopping cart monitoring in Django Admin."""

    list_display = (
        "id",
        "owner_display",
        "total_items_display",
        "subtotal_display",
        "created_at",
        "updated_at",
    )

    list_filter = (
        "created_at",
        "updated_at",
    )

    search_fields = (
        "user__username",
        "user__email",
        "session_key",
    )

    readonly_fields = (
        "user",
        "session_key",
        "total_items_display",
        "subtotal_display",
        "created_at",
        "updated_at",
    )

    inlines = [
        CartItemInline,
    ]

    fieldsets = (
        (
            "Cart Owner",
            {
                "fields": (
                    "user",
                    "session_key",
                )
            },
        ),
        (
            "Cart Summary",
            {
                "fields": (
                    "total_items_display",
                    "subtotal_display",
                )
            },
        ),
        (
            "System Information",
            {
                "fields": (
                    "created_at",
                    "updated_at",
                )
            },
        ),
    )

    def has_add_permission(self, request):
        """Carts should be generated by the storefront."""

        return False

    @admin.display(description="Owner")
    def owner_display(self, obj):
        if obj.user:
            return obj.user.username

        short_key = obj.session_key[:12]
        return f"Guest session: {short_key}..."

    @admin.display(description="Total Items")
    def total_items_display(self, obj):
        return obj.total_items

    @admin.display(description="Subtotal")
    def subtotal_display(self, obj):
        return f"Rs. {obj.subtotal:,.2f}"


@admin.register(CartItem)
class CartItemAdmin(admin.ModelAdmin):
    """Configure cart item monitoring in Django Admin."""

    list_display = (
        "product",
        "variant",
        "cart_owner_display",
        "quantity",
        "unit_price_display",
        "line_total_display",
        "updated_at",
    )

    list_filter = (
        "product__category",
        "variant__size",
        "variant__color_name",
        "created_at",
    )

    search_fields = (
        "product__name",
        "product__sku",
        "variant__sku",
        "cart__user__username",
        "cart__session_key",
    )

    readonly_fields = (
        "cart",
        "product",
        "variant",
        "quantity",
        "unit_price_display",
        "line_total_display",
        "created_at",
        "updated_at",
    )

    list_select_related = (
        "cart",
        "cart__user",
        "product",
        "variant",
    )

    def has_add_permission(self, request):
        """Cart items should be generated by the storefront."""

        return False

    @admin.display(description="Cart Owner")
    def cart_owner_display(self, obj):
        if obj.cart.user:
            return obj.cart.user.username

        short_key = obj.cart.session_key[:12]
        return f"Guest: {short_key}..."

    @admin.display(description="Unit Price")
    def unit_price_display(self, obj):
        return f"Rs. {obj.unit_price:,.2f}"

    @admin.display(description="Line Total")
    def line_total_display(self, obj):
        return f"Rs. {obj.line_total:,.2f}"